### PR TITLE
Fix for the sample project so that it can compile with the current rbfx

### PR DESCRIPTION
**Pull request by crystaldev3d**
hello, check this plz

### CODE REVIEW

**Comment by rokups** [comment]
Hey thanks for the PR! Could you also fix this failure?
> Source/MenuGameScreen.h:32:35: error: non-virtual member function marked 'override' hides virtual member function

**Comment by crystaldev3d** [comment]
vs2022 didn't complain about anything
 using final is ok ?

**Comment by rokups** [comment]
Some compilers are stricter than others 🙃 Yeah `final` does not hurt.

**Comment by rokups** [comment]
> error: non-virtual member function marked 'final' hides virtual member function

I forgot that `final` is meant to make virtuals non-overridable, so yeah it has to be removed 🙃

**Comment by rokups** [comment]
> MenuGameScreen.cpp:54:46: error: use of undeclared identifier 'GetDataModelConstructor'; did you mean 'Rml::DataModelConstructor'?

Web build is really testing your patience 👀

**Comment by crystaldev3d** [comment]
Yes, I meant exactly Rml::DataModelConstructor
It could not be passed through the constructor, as before, so I get it through GetDataModelConstructor, I thought it could be done that way and there is nothing wrong with it )

**Comment by crystaldev3d** [comment]
Okay, one last try and I give up 
I don't understand why it doesn't see the GetDataModelConstructor method, since it is defined in the MainMenuWindow's base class.

**Comment by rokups** [comment]
K, if it doesnt work ill fix it myself and push to this branch and merge it 👍 you did most of the work anyway, thanks :)

**Comment by eugeneko** [comment]
@rokups ah, it's not that easy to update because we need to have native SDK now

**Comment by eugeneko** [comment]
Fixed in https://github.com/rbfx/sample-project/commit/da953e3c487b1168ee9d0a19abfb07f80d84376e

**Pull request closed without merging**
