### PR TITLE
fix SampleProjectLauncher link error

### PR DESCRIPTION
**Pull request by aimoonchen**

### CODE REVIEW

**Comment by rokups** [comment]
Could you describe how you built everything (cmake CMD line) and what error you got? Thingy you removed was there for a reason.

**Comment by eugeneko** [comment]
@gleblebedev that's yours

**Comment by eugeneko** [comment]
By the way, you should never link `_StaticPlugins` targets manually.

**Comment by gleblebedev** [comment]
> By the way, you should never link `_StaticPlugins` targets manually.

How would I get the plugins any other way?

**Comment by eugeneko** [comment]
Same way Player and Editor do it.

**Comment by gleblebedev** [comment]
Thank you for bringing it to my attention. The issue is fixed now.

Beware: there is problem with command line args in the main repo for now.

**Pull request closed without merging**
